
# FILENAME: .github/workflows/ci.yml
name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ENVIRONMENT SETUP
      - name: Setup C++ Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make valgrind # Install build tools and memory checker

      # DEPENDENCY CACHING (Not applicable for this project type, but leaving placeholder)
      # Add caching if a package manager is used in the future.

      # LINTING STAGE (Auto-configuring with cpplint - basic example, improve as needed.)
      - name: Install cpplint
        run: |
          curl https://raw.githubusercontent.com/google/cpplint/master/cpplint > cpplint.py
          chmod +x cpplint.py

      - name: Run Linter (cpplint)
        run: |
          ./cpplint --verbose *.cpp *.h 
          # QUALITY GATE: Fails on style violations - adjust options as needed for project standards.

      # BUILD STAGE
      - name: Configure CMake
        run: cmake .

      - name: Build project
        run: make
        # QUALITY GATE: Fails on compilation errors

      # TEST STAGE
      - name: Run tests (example)
        run: ./main # Using provided test command.  Could be more specific if needed.
        # QUALITY GATE: Fails on test failures
