
# FILENAME: .github/workflows/ci.yml
name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake  # Install necessary tools
        echo "C++ environment setup complete."

    # DEPENDENCY CACHING (Not applicable for this project, no package manager)
    #- name: Cache dependencies
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.cache/pip
    #    key: ${{ runner.os }}-deps-${{ hashFiles('requirements.txt') }}

    # LINTING STAGE (Using clang-format as a default C++ linter)
    - name: Install clang-format
      run: |
        sudo apt-get install -y clang-format

    - name: Run Linter (clang-format)
      run: |
        find . -name "*.cpp" -print0 | xargs -0 clang-format --style=Google --dry-run || exit 1  # Check for formatting issues. Exit if violations found.
      # QUALITY GATE: Fails on style violations

    # BUILD STAGE
    - name: Build project
      run: g++ -std=c++17 *.cpp -o main # Builds all .cpp files in the current directory
      # QUALITY GATE: Fails on compilation errors

    # TEST STAGE
    - name: Run tests
      run: ./main # Executes the compiled program.  Assumes 'main' is the test executable.
      # QUALITY GATE: Fails on test failures
